apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
data:
  STRIPE_KEY: c2tfdGVzdF81MUo2MkZjQzVjeE9Tc3BzVVdRUFo4b0dCOEl4aXV0dkw4NGtTV3V6NzRWTGFKRDZHOER5VW5PUTIwRHVnOWxUcXFmOU5VTWRRYzZISXpoYWVFTGVzYzRWYzAwbVdLZkxzc0I=
